language: java
jdk:
    - oraclejdk8

addons:
   sonarcloud:
      organization: "csc308"
      token:
         secure: "439d274c235b5495e606d970059789551e2b694c"
         script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar \
